# Generated by Django 4.2.6 on 2023-11-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('prize', models.FloatField()),
            ],
        ),
    ]
