# Generated by Django 4.2.6 on 2023-11-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_CustomUser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
